"""Reproducible, original smooth-union models; run in Blender's Python.

blender --background --factory-startup --python tools/build_sculpted_assets.py
Only the temporary factory scene is changed. OBJ files contain triangles/normals.
"""
import bpy
import json
import math
from pathlib import Path

OUT = Path(__file__).resolve().parents[1] / "assets" / "models"
OUT.mkdir(parents=True, exist_ok=True)
stats = {}


def ellipsoid(position, scale, rotation=(0, 0, 0)):
    bpy.ops.mesh.primitive_uv_sphere_add(segments=32, ring_count=20, location=position)
    obj = bpy.context.object
    obj.scale = scale
    obj.rotation_euler = rotation
    bpy.ops.object.transform_apply(location=True, rotation=True, scale=True)
    return obj


def sculpt(name, shapes, voxel, ratio=0.5):
    bpy.ops.object.select_all(action="DESELECT")
    parts = [ellipsoid(*shape) for shape in shapes]
    for obj in parts:
        obj.select_set(True)
    bpy.context.view_layer.objects.active = parts[0]
    bpy.ops.object.join()
    obj = bpy.context.object
    obj.name = name
    remesh = obj.modifiers.new("Seamless inflated surface", "REMESH")
    remesh.mode = "VOXEL"
    remesh.voxel_size = voxel
    remesh.use_smooth_shade = True
    bpy.ops.object.modifier_apply(modifier=remesh.name)
    smooth = obj.modifiers.new("Relax the seams", "SMOOTH")
    smooth.factor = 1.2
    smooth.iterations = 5
    bpy.ops.object.modifier_apply(modifier=smooth.name)
    reduce = obj.modifiers.new("Quest silhouette budget", "DECIMATE")
    reduce.ratio = ratio
    bpy.ops.object.modifier_apply(modifier=reduce.name)
    for polygon in obj.data.polygons:
        polygon.use_smooth = True
    obj.data.calc_loop_triangles()
    mesh = obj.data
    # Coordinates are authored in Godot convention, so the OBJ stores them directly.
    # Godot's OBJ importer converts the standard counterclockwise faces itself.
    lines = ["# Original Foam Haven sculpt. Generated by build_sculpted_assets.py"]
    for vertex in mesh.vertices:
        lines.append("v %.6f %.6f %.6f" % tuple(vertex.co))
    for vertex in mesh.vertices:
        n = vertex.co.normalized()
        u = math.atan2(n.z, n.x) / math.tau + 0.5
        v = math.acos(max(-1, min(1, n.y))) / math.pi
        lines.append("vt %.6f %.6f" % (u, v))
    for vertex in mesh.vertices:
        lines.append("vn %.6f %.6f %.6f" % tuple(vertex.normal))
    for tri in mesh.loop_triangles:
        ids = [i + 1 for i in tri.vertices]
        lines.append("f " + " ".join(f"{i}/{i}/{i}" for i in ids))
    (OUT / f"{name}.obj").write_text("\n".join(lines) + "\n")
    stats[name] = {"vertices": len(mesh.vertices), "triangles": len(mesh.loop_triangles)}
    assert len(mesh.loop_triangles) < 18000, (name, stats[name])
    bpy.data.objects.remove(obj, do_unlink=True)


sculpt("duck_body", [
    ((0, 0, 0), (0.62, 0.42, 0.8)),
    ((0, 0.43, -0.43), (0.27, 0.4, 0.28)),
    ((0, 0.76, -0.5), (0.37, 0.37, 0.37)),
    ((0, 0.16, 0.68), (0.27, 0.22, 0.39), (-0.4, 0, 0)),
], 0.035, 0.55)
sculpt("dolphin_body", [
    ((0, 0, 0), (0.4, 0.43, 1.02)),
    ((0, 0.06, -0.81), (0.32, 0.32, 0.42)),
    ((0, -0.04, -1.18), (0.13, 0.105, 0.40)),
    ((0, 0, 0.9), (0.18, 0.20, 0.45)),
    ((0, 0.48, 0.1), (0.065, 0.30, 0.25), (-0.35, 0, 0)),
] + [
    ((side * 0.48, -0.15, -0.1), (0.43, 0.06, 0.17), (0, side * -0.55, 0))
    for side in (-1, 1)
] + [
    ((side * 0.28, 0, 1.19), (0.39, 0.075, 0.21), (0, side * 0.25, 0))
    for side in (-1, 1)
], 0.028, 0.45)
for variant in range(3):
    shapes = [((0, -0.18, 0), (2.55, 0.52, 1.13))]
    for i in range(7):
        shapes.append(((math.sin(i * 2.1 + variant) * 1.8,
                        0.05 + math.cos(i * 2.3 + variant) * 0.26,
                        math.cos(i * 1.7 + variant) * 0.67),
                       (0.86 + (i % 3) * 0.10, 0.60 + (i % 2) * 0.30, 0.94)))
    sculpt(f"cloud_{variant}", shapes, 0.115, 0.60)
(OUT / "geometry.json").write_text(json.dumps(stats, indent=2) + "\n")
print("SCULPTED_ASSETS_OK", json.dumps(stats))
